Add files via upload

diff --git a/DnD b/DnD
--- a/DnD
+++ b/DnD
@@ -2,7 +2,7 @@
 
 echo "Welcome Adventurer!" 
 read -p "What is your name? " name
-
+echo "$name, you are on a quest to save your village after the harvest failed."
 
 age_check(){
 echo "You approach a tavern."
@@ -111,46 +111,56 @@ tavern_stealth
 read -p "$name would you like to roll for int, str or magic? " trapdoor
 
 trapdoor_int(){
+ 
+ local roll=$(( $RANDOM % 10))
+ echo "You rolled a $roll"
+ 
  if (( $roll >=5))
  then 
  	echo "You notice an elven puzzle lock. You solve it successfully."
  	return 1
  else 
  	echo "You notice an elven puzzle lock. You are unable to solve it."
- 	read -p "Would you like to roll for str or magic? " try_again
+ 	read -p "Would you like to roll for str or magic? " trapdoor
 	return 0
  fi
 }
 
 
 trapdoor_str(){
+ 
+ local roll=$(( $RANDOM % 10))
+ echo "You rolled a $roll"
+
  if (( $roll >=5))
  then 
  	echo "You pull the trapdoor open, breaking its hinges."
 	return 1
  else 
  	echo "You attempt to pull open the trapdoor but it doesn't budge."
- 	read -p "Would you like to roll for int or magic? " try_again
+ 	read -p "Would you like to roll for int or magic? " trapdoor
 	return 0
  fi
 
 }
 
 trapdoor_magic(){
+
+ local roll=$(( $RANDOM % 10))
+ echo "You rolled a $roll"
+
  if (( $roll >=5))
  then 
  	echo "You enchant the trapdoor, opening the lock."
  	return 1
  else
  	echo "You whisper a spell but cannot open the trapdoor."
- 	read -p "Would you like to roll for int or str? " try_again
+ 	read -p "Would you like to roll for int or str? " trapdoor
  	return 0
  fi
 }
 
 open_trapdoor(){
- local roll=$(( $RANDOM % 10))
- echo "You rolled a $roll"
 
  if [ "$trapdoor" == "int" ]
  then 
@@ -172,23 +182,26 @@ open_trapdoor(){
 
 open_trapdoor
 
-open_true(){
- if (( $open == 1))
- then
- 	echo "You feel a chill as you enter the basement"
- 	read -p "Would you like to roll for per or magic to look around? " look_basement
- else (( $open == 0))
- 	case $try_again in
-	"int") trapdoor_int;;
- 	"magic") trapdoor_magic;;
- 	"str") trapdoor_str;;
+open_true(){ 
+ while (( $open == 0))
+ do
+ 	case $trapdoor in
+	"int") open_trapdoor;;
+ 	"magic") open_trapdoor;;
+ 	"str") open_trapdoor;;
 	esac
- fi
+ done
 }
 
 open_true
 
+
+
+
 in_basement(){
+ echo "You feel a chill as you enter the basement"
+ read -p "Would you like to roll for per or magic to look around? " look_basement
+
  local roll=$(( $RANDOM % 10))
  echo "You rolled a $roll"
 
@@ -197,15 +210,19 @@ in_basement(){
  	if (( $roll >=5))
  	then 
  		echo "Your eyes adjust to the darkness and you notice a treasure chest"
+ 		return 1
  	else
- 		read -p "You notice a torch. Would you like to light it? Yes/no " torch
+ 		read -p "You notice a torch. Would you like to light it? yes/no " torch
+ 		return 0
  	fi
  else [ "$look_basement" == "magic" ]
  	if (( $roll >=5))
  	then
  		echo "You summon a glowing orb of light"
+ 		return 1
  	else 
- 		read -p "Your magical light orb sputters out. From its brief glow you notice a torch on the wall. Would you like to light it? Yes/no " torch
+ 		read -p "Your magical light orb sputters out. From its brief glow you notice a torch on the wall. Would you like to light it? yes/no " torch
+ 		return 0
 	fi
 
  fi
@@ -213,6 +230,49 @@ in_basement(){
 }
 
 in_basement
+lit=$?
+
+
+open_chest(){
+ read -p "The chest hums with energy. Would you like to roll for per or magic? " chest
+
+ if [ "$chest" == "per" ]
+ then 
+ 	echo "You notice an antique key in a sack of grain. You open the chest."
+ else [ "$chest" == "magic" ]
+ 	echo "You enchant the lock, opening the chest."
+ fi
+}
+
+
+light_torch(){
+
+ if (( $lit ==0))
+ then 
+ 	if [ "$torch" == "yes" ]
+ 	then
+ 		echo "You light the torch and notice a treasure chest"
+ 		open_chest
+ 	else 
+ 		echo "You stumble around in the darkness until you trip over a treasure chest."
+ 		open_chest
+ 	fi
+ else
+ 	open_chest
+ fi
+}
+
+light_torch
+
+
+echo "You take the treasure home and distribute it amongst the villagers. You have saved your town from starvation in the winter ahead. Congratulations, $name, you are a hero!"
+
+
+
+
+
+
+
 
 
 
